name: 'Hello World Action'
description: 'A simple hello world action'
author: 'Chandan Mohan'

inputs:
  name:
    description: 'Who to say hello to'
    required: true
    default: 'World'

runs:
  using: 'node12'
  main: 'index.js'
