name: Checking Custom Action

on:
  push:
    branches:
      - master

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/hello-world-action
      - name: Use local hello-world-action
        id: hello # This is the ID of the step
        uses: ./.github/actions/hello-world-action
        with:
          name: 'GitHub User'
      - name: Display greeting
        run: |
          echo "Greeting: ${{ steps.hello.outputs.greetingMessage }}"
